# Generated by Django 3.2.9 on 2021-12-05 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0002_physicalport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_app.user'),
        ),
    ]
